"""user_avatar_key

Revision ID: bef92f52c3b9
Revises: 83bb517220de
Create Date: 2026-02-26 21:49:30.386462

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bef92f52c3b9"
down_revision: Union[str, Sequence[str], None] = "83bb517220de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_key", sa.String(), nullable=True))
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("avatar_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "avatar_key")
    # ### end Alembic commands ###
